title: Keep Calm and DCA On
description: Invest consistently through every market.
url: "https://keepcalmanddcaon.com"
baseurl: ""
lang: en
markdown: kramdown
plugins:
  - jekyll-seo-tag
exclude:
  - node_modules
  - vendor
  - tests
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
